### ISSUE TITLE
Update readme reference to JWT Token Generator needed for "Shared Secret" tab

### ISSUE THREAD

**Issue by osowski** [ibm-cloud-architecture/refarch-cloudnative-devops#20]
Clicking on the link to the external JWT Token Generator takes you to the RSA tab and is easily confused as the correct place you need to be to generate the token.  However, you need to click on the "Shared Secret" tab to create the correct type of key.

**Comment by gangchen03** [comment]
Should use the common instruction of setting JWT key at https://github.com/ibm-cloud-architecture/refarch-cloudnative/blob/master/static/security.md#generate-jwt-shared-key. Please update the doc.

**Comment by ssibm** [comment]
patched in pr:21. closed.
